---
name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Run at 1:10 on Sunday
    - cron: "10 1 * * 0"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm
          - arm64
          - amd64
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Build the image with Buildah
        run: ./gcc-image.sh -a ${{ matrix.arch }}

      - name: Tag the image for Fedora 34
        run: podman tag localhost/gcc localhost/gcc:34

      - name: Export the image
        run: podman image save --format oci-archive -o gcc-${{ matrix.arch }}.tar localhost/gcc

      - uses: actions/upload-artifact@v2
        with:
          name: gcc-${{ matrix.arch }}
          path: gcc-${{ matrix.arch }}.tar

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        arch:
          - arm
          - arm64
          - amd64
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: gcc-${{ matrix.arch }}

      - name: Load the image
        run: podman image load -i gcc-${{ matrix.arch }}.tar

      - name: Run the image and verify GCC is available inside the container
        run: podman run --rm --volume "$PWD":/home/user:Z --name test-container localhost/gcc g++ test/main.cpp
  
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Create a manifest
        run: buildah manifest create gcc-multiarch:latest

      # armhfp
      - uses: actions/download-artifact@v2
        with:
          name: gcc-arm

      - name: Load the arm64 image
        run: podman image load -i gcc-arm.tar
              
      - name: Add the arm image to the manifest
        run: buildah manifest add gcc-multiarch:latest localhost/gcc

      # aarch64
      - uses: actions/download-artifact@v2
        with:
          name: gcc-arm64

      - name: Load the arm64 image
        run: podman image load -i gcc-arm64.tar
              
      - name: Add the arm64 image to the manifest
        run: buildah manifest add gcc-multiarch:latest localhost/gcc

      # x86_64
      - uses: actions/download-artifact@v2
        with:
          name: gcc-amd64

      - name: Load the amd64 image
        run: podman image load -i gcc-amd64.tar

      - name: Add the amd64 image to the manifest
        run: buildah manifest add gcc-multiarch:latest localhost/gcc

      - name: Push latest manifest and images to quay.io
        run: buildah manifest push --rm --all --creds jwillikers+publisher:${{ secrets.REGISTRY_PASSWORD }} gcc-multiarch:latest docker://quay.io/jwillikers/gcc
